services:
  redis:
    image: redis:8.0-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - default
      - finance_network

  redisinsight:
    image: redis/redisinsight:3.4.1
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis
    networks:
      - default
      - finance_network

volumes:
  redis_data:
    driver: local
  redisinsight_data:
    driver: local

networks:
  finance_network:
    external: true
