services:
  mlflow-server:
    init: true
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    image: ghcr.io/mlflow/mlflow:v3.14.0
    container_name: mlflow-server
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.50
    pids_limit: 256
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    networks:
      - finance_network
    command: >
      mlflow server 
      --backend-store-uri postgresql://${POSTGRES_USER_MLFLOW}:${POSTGRES_PASSWORD_MLFLOW}@${POSTGRES_HOST_MLFLOW}:${POSTGRES_PORT_MLFLOW}/${POSTGRES_DB_MLFLOW}
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --host 0.0.0.0
      --port 5000
      --workers 1

volumes:
  mlflow_artifacts:

networks:
  finance_network:
    external: true
    name: finance_network
